<a href="https://colab.research.google.com/github/marginli/NSYSU2021/blob/main/Python_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# magnitude of a 3D vector

In [20]:
x=1.0
print("x component is",x)
y=2.0
print("y component is",y)
z=3.0
print("z component is",z)
r=pow(x**2+y**2+z**2,0.5)
print("the magnitude of this vector is",r)

x component is 1.0
y component is 2.0
z component is 3.0
the magnitude of this vector is 3.7416573867739413


In [ ]:
# moving right or left 

In [22]:
v=float(input("give me your velocity  :"))
if v>0:
    print("moving right")
elif v<0:
    print("moving left")
else :
    print("not moving")

give me your velocity  :-9
moving left


In [ ]:
# moving or not moving

In [23]:
from numpy.random import random
force=0.0
ran_fric=random()
mass=10.0
while force<mass*ran_fric :
    print("haha! you cannot move me!!")
    force_add=float(input("add some force!!"))
    force=force+force_add
print("Ah... you win...")
print("the friction coefficient is :",ran_fric)
print("the estimated friction coefficient is :",force/mass)

haha! you cannot move me!!
add some force!!1
Ah... you win...
the friction coefficient is : 0.02068305996845432
the estimated friction coefficient is : 0.1


In [ ]:
# calculating factorial

In [25]:
n=int(input("give me an integer, I will give you the factorial"))
factorial=1
for i in range(n):
    factorial=factorial*(i+1)
print("the value of",n,"!","is",factorial)

give me an integer, I will give you the factorial5
the value of 5 ! is 120


In [ ]:
# eigenvalue problem

In [26]:
import numpy as np
H=np.array([[1,4,6],[4,2,5],[6,5,3]])
w,v=np.linalg.eig(H)
print("the eigenvalues are ",w)
print("the eigenvectors are")
print(v)

the eigenvalues are  [12.12839341 -4.09460205 -2.03379136]
the eigenvectors are
[[-0.54185054 -0.73860675  0.40107113]
 [-0.53428068 -0.06566881 -0.84275249]
 [-0.64880055  0.67093045  0.35904064]]


In [ ]:
# load files

In [19]:
import numpy as np
ex_data=np.loadtxt("https://raw.githubusercontent.com/marginli/NSYSU2021/main/external_file.txt") # loading txt files from an online URL
#ex_data=np.loadtxt("external_file.txt") #loading local txt files
print(ex_data)

[[0.0361525 0.0361525 0.0261422 0.0261422]
 [0.0261422 0.0261422 0.0235028 0.0235028]
 [0.0235028 0.0235028 0.0307595 0.0307595]
 [0.0307595 0.0307595 0.0285627 0.0285627]
 [0.0285627 0.0285627 0.0307596 0.0307596]
 [0.0307596 0.0307596 0.0235044 0.0235044]
 [0.0235044 0.0235044 0.0261397 0.0261397]
 [0.0261397 0.0261397 0.0361525 0.0361525]
 [0.0361525 0.0361525 0.0261428 0.0261428]
 [0.0261428 0.0261428 0.0235023 0.0235023]
 [0.0235023 0.0235023 0.0307594 0.0307594]
 [0.0307594 0.0307594 0.0285629 0.0285629]
 [0.0285629 0.0285629 0.0307595 0.0307595]
 [0.0307595 0.0307595 0.0235039 0.0235039]
 [0.0235039 0.0235039 0.0261402 0.0261402]
 [0.0261402 0.0261402 0.0361525 0.0361525]
 [0.0361525 0.0361525 0.0261422 0.0261422]
 [0.0261422 0.0261422 0.0235028 0.0235028]
 [0.0235028 0.0235028 0.0307595 0.0307595]
 [0.0307595 0.0307595 0.0285627 0.0285627]
 [0.0285627 0.0285627 0.0307596 0.0307596]
 [0.0307596 0.0307596 0.0235044 0.0235044]
 [0.0235044 0.0235044 0.0261397 0.0261397]
 [0.0261397

In [ ]:
# define a function to calculate factorial

In [28]:
def fac_cal(n):
    result=1
    for i in range(n):
        result=result*(i+1)
    return result
m=int(input("give me an integer, I will give you the factorial "))
res=fac_cal(m)
print(m,"!","=",res)

give me an integer, I will give you the factorial6
6 ! = 720
